import { jsx as _jsx, jsxs as _jsxs } from "preact/jsx-runtime";
import { useEffect } from 'preact/hooks';
import { categories, selectedCategory, categoriesLoading, categoriesError, isSelectingCategory, fetchCategories, selectCategory, clearCategorySelection, } from '../state/categories';
import { currentUser, logout } from '../state/auth';
import { startNewBookingFlow, openBookingHistory } from '../state/booking';
import { currentLanguage, selectLanguage, t } from '../state/language';
import { CategoryIconRenderer, PhoneIcon, WhatsAppIcon, CheckIcon, AlertCircleIcon, SpinnerIcon, LogOutIcon, FileTextIcon, } from './icons';
import { supportPhone, supportWhatsApp, fetchSupportConfig } from '../state/config';
export function CustomerHome() {
    useEffect(() => {
        fetchCategories();
        fetchSupportConfig();
    }, []);
    const lang = currentLanguage.value || 'en';
    const user = currentUser.value;
    const phone = supportPhone.value;
    const rawWhatsApp = supportWhatsApp.value;
    const cleanWhatsApp = rawWhatsApp ? rawWhatsApp.replace(/[^0-9]/g, '') : null;
    const whatsappUrl = cleanWhatsApp
        ? `https://wa.me/${cleanWhatsApp}?text=${encodeURIComponent('Hello Chandil Home Services')}`
        : null;
    const getCategoryTitle = (cat) => {
        return lang === 'hi' ? cat.titleHi : cat.titleEn;
    };
    const getCategoryDesc = (cat) => {
        return lang === 'hi' ? (cat.descHi || '') : (cat.descEn || '');
    };
    return (_jsxs("div", { class: "min-h-screen flex flex-col bg-background", children: [_jsx("header", { class: "bg-brand text-white px-4 py-3 shadow-sm sticky top-0 z-10", children: _jsxs("div", { class: "max-w-md mx-auto flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h1", { class: "text-base font-bold leading-tight", children: t('app.title') }), _jsx("p", { class: "text-xs text-slate-300 leading-tight", children: t('home.service_area_label') })] }), _jsxs("div", { class: "flex items-center space-x-2", children: [_jsxs("div", { class: "flex items-center bg-brand-dark p-0.5 rounded border border-slate-600", children: [_jsx("button", { onClick: () => selectLanguage('en'), class: `px-2 py-1 text-xs font-semibold rounded min-h-[32px] transition-colors ${lang === 'en'
                                                ? 'bg-action text-white'
                                                : 'text-slate-300 hover:text-white'}`, "aria-label": "Switch to English", children: "EN" }), _jsx("button", { onClick: () => selectLanguage('hi'), class: `px-2 py-1 text-xs font-semibold rounded min-h-[32px] transition-colors ${lang === 'hi'
                                                ? 'bg-action text-white'
                                                : 'text-slate-300 hover:text-white'}`, "aria-label": "\u0939\u093F\u0902\u0926\u0940 \u092D\u093E\u0937\u093E \u091A\u0941\u0928\u0947\u0902", children: "\u0939\u093F\u0902\u0926\u0940" })] }), _jsx("button", { onClick: () => logout(), class: "p-2 text-slate-300 hover:text-white rounded min-h-[40px] min-w-[40px] flex items-center justify-center border border-slate-600 hover:border-slate-400", title: t('auth.logout'), "aria-label": t('auth.logout'), children: _jsx(LogOutIcon, { size: 18 }) })] })] }) }), user && (_jsx("section", { class: "bg-slate-100 border-b border-border px-4 py-2", children: _jsxs("div", { class: "max-w-md mx-auto flex items-center justify-between text-xs text-text-sub", children: [_jsx("span", { class: "font-medium text-text-main", children: t('auth.logged_in_as', { phone: `+91 ${user.phone}` }) }), _jsxs("button", { onClick: () => openBookingHistory(), class: "px-2.5 py-1 bg-white hover:bg-slate-50 border border-slate-300 text-brand font-bold rounded text-xs transition-colors flex items-center space-x-1 shadow-2xs min-h-[36px]", "aria-label": t('history.title'), children: [_jsx(FileTextIcon, { size: 14 }), _jsx("span", { children: t('history.title') })] })] }) })), _jsxs("main", { class: "flex-1 p-4 max-w-md mx-auto w-full space-y-4", children: [_jsxs("section", { class: "bg-surface border border-border rounded-lg p-4 shadow-sm", children: [_jsx("h2", { class: "text-lg font-bold text-text-main leading-tight mb-1", children: t('home.service_heading') }), _jsx("p", { class: "text-xs text-text-sub leading-relaxed", children: t('app.tagline') })] }), selectedCategory.value && (_jsxs("section", { class: "bg-green-50 border-2 border-action rounded-lg p-4 shadow-sm space-y-3", children: [_jsxs("div", { class: "flex items-start justify-between space-x-3", children: [_jsxs("div", { class: "flex items-start space-x-2", children: [_jsx(CheckIcon, { size: 20, class: "text-action mt-0.5 shrink-0" }), _jsxs("div", { children: [_jsx("div", { class: "text-sm font-bold text-action-active leading-tight", children: t('home.selected_category_notice', {
                                                            title: getCategoryTitle(selectedCategory.value),
                                                        }) }), _jsx("div", { class: "text-xs text-text-sub mt-1", children: t('home.visit_charge', { amount: selectedCategory.value.baseVisitFee }) })] })] }), _jsx("button", { onClick: () => clearCategorySelection(), class: "text-xs font-semibold text-text-sub hover:text-danger p-1 min-h-[32px] shrink-0 underline", children: t('app.cancel') })] }), _jsxs("button", { onClick: () => startNewBookingFlow(selectedCategory.value), class: "w-full min-h-[44px] px-4 py-2.5 bg-action hover:bg-action-active text-white font-bold rounded-lg text-sm flex items-center justify-center space-x-1.5 shadow-sm transition-colors", children: [_jsx("span", { children: t('booking.continue_to_book') }), _jsx("span", { children: "\u2192" })] })] })), categoriesLoading.value && (_jsxs("div", { class: "bg-surface border border-border rounded-lg p-8 flex flex-col items-center justify-center space-y-3", children: [_jsx(SpinnerIcon, { size: 32, class: "text-brand" }), _jsx("p", { class: "text-sm font-semibold text-text-sub", children: t('app.loading') })] })), !categoriesLoading.value && categoriesError.value && (_jsxs("div", { class: "bg-surface border border-red-200 rounded-lg p-5 shadow-sm space-y-3", children: [_jsxs("div", { class: "flex items-start space-x-3 text-danger", children: [_jsx(AlertCircleIcon, { size: 24, class: "shrink-0 mt-0.5" }), _jsxs("div", { children: [_jsx("h3", { class: "text-sm font-bold", children: t('app.network_error') }), _jsx("p", { class: "text-xs text-text-sub mt-1", children: categoriesError.value })] })] }), _jsx("button", { onClick: () => fetchCategories(), class: "w-full min-h-[48px] px-4 py-2.5 bg-brand hover:bg-brand-dark text-white font-bold rounded-lg text-sm transition-colors flex items-center justify-center", children: t('app.retry') })] })), !categoriesLoading.value && !categoriesError.value && categories.value.length === 0 && (_jsxs("div", { class: "bg-surface border border-border rounded-lg p-6 text-center space-y-3", children: [_jsx("p", { class: "text-sm text-text-sub", children: t('home.empty_categories') }), _jsx("button", { onClick: () => fetchCategories(), class: "min-h-[48px] px-6 py-2 bg-brand text-white font-semibold rounded-lg text-sm hover:bg-brand-dark transition-colors", children: t('app.retry') })] })), !categoriesLoading.value && !categoriesError.value && categories.value.length > 0 && (_jsx("section", { class: "space-y-3", "aria-label": "Service Categories", children: categories.value.map((cat) => {
                            const isSelected = selectedCategory.value?.id === cat.id;
                            const isDisabled = !cat.isActive || isSelectingCategory.value;
                            return (_jsxs("button", { onClick: () => selectCategory(cat), disabled: isDisabled, "aria-pressed": isSelected, class: `w-full text-left p-4 rounded-lg border-2 transition-all flex items-center justify-between min-h-[76px] ${!cat.isActive
                                    ? 'bg-slate-100 border-slate-200 opacity-60 cursor-not-allowed'
                                    : isSelected
                                        ? 'bg-green-50/60 border-action shadow-sm'
                                        : 'bg-surface border-border hover:border-brand active:bg-slate-50 cursor-pointer'}`, children: [_jsxs("div", { class: "flex items-center space-x-3.5 flex-1 pr-2", children: [_jsx("div", { class: `w-12 h-12 rounded-lg flex items-center justify-center shrink-0 ${isSelected
                                                    ? 'bg-action text-white'
                                                    : !cat.isActive
                                                        ? 'bg-slate-200 text-slate-400'
                                                        : 'bg-brand/10 text-brand'}`, children: _jsx(CategoryIconRenderer, { iconName: cat.iconName, size: 26 }) }), _jsxs("div", { class: "flex-1 min-w-0", children: [_jsxs("div", { class: "flex items-center justify-between", children: [_jsx("span", { class: "text-base font-bold text-text-main leading-tight truncate", children: getCategoryTitle(cat) }), !cat.isActive && (_jsx("span", { class: "text-[11px] font-semibold text-warning bg-amber-50 border border-amber-200 px-1.5 py-0.5 rounded ml-2 shrink-0", children: t('home.category_unavailable') }))] }), _jsx("p", { class: "text-xs text-text-sub leading-normal mt-0.5 line-clamp-2", children: getCategoryDesc(cat) }), _jsx("div", { class: "text-xs font-semibold text-action mt-1", children: t('home.visit_charge', { amount: cat.baseVisitFee }) })] })] }), _jsx("div", { class: "shrink-0 pl-1", children: isSelected ? (_jsx("div", { class: "w-7 h-7 rounded-full bg-action text-white flex items-center justify-center", children: _jsx(CheckIcon, { size: 16 }) })) : (_jsx("div", { class: "w-7 h-7 rounded-full border-2 border-slate-300 flex items-center justify-center text-slate-300", children: _jsx("span", { class: "text-xs", children: "\u2192" }) })) })] }, cat.id));
                        }) })), _jsxs("section", { class: "bg-surface border border-border rounded-lg p-4 shadow-sm space-y-3", children: [_jsx("h3", { class: "text-xs font-bold text-text-sub uppercase tracking-wider", children: t('app.help') }), _jsxs("div", { class: "grid grid-cols-1 sm:grid-cols-2 gap-2.5", children: [phone ? (_jsxs("a", { href: `tel:${phone}`, class: "min-h-[48px] px-3 py-2.5 border-2 border-brand text-brand hover:bg-brand hover:text-white rounded-lg font-semibold text-xs transition-colors flex items-center justify-center space-x-2 text-center", children: [_jsx(PhoneIcon, { size: 18 }), _jsx("span", { children: t('home.call_to_book') })] })) : (_jsxs("button", { type: "button", disabled: true, class: "min-h-[48px] px-3 py-2.5 border-2 border-slate-200 text-slate-400 rounded-lg font-semibold text-xs flex items-center justify-center space-x-2 text-center cursor-not-allowed opacity-60", children: [_jsx(PhoneIcon, { size: 18 }), _jsx("span", { children: t('home.call_to_book') })] })), whatsappUrl ? (_jsxs("a", { href: whatsappUrl, target: "_blank", rel: "noopener noreferrer", class: "min-h-[48px] px-3 py-2.5 bg-action hover:bg-action-active text-white rounded-lg font-semibold text-xs transition-colors flex items-center justify-center space-x-2 text-center", children: [_jsx(WhatsAppIcon, { size: 18 }), _jsx("span", { children: t('home.whatsapp_to_book') })] })) : (_jsxs("button", { type: "button", disabled: true, class: "min-h-[48px] px-3 py-2.5 bg-slate-200 text-slate-400 rounded-lg font-semibold text-xs flex items-center justify-center space-x-2 text-center cursor-not-allowed opacity-60", children: [_jsx(WhatsAppIcon, { size: 18 }), _jsx("span", { children: t('home.whatsapp_to_book') })] }))] })] })] }), _jsx("footer", { class: "bg-surface border-t border-border p-3 max-w-md mx-auto w-full", children: _jsxs("div", { class: "flex items-center justify-between text-xs text-text-sub", children: [_jsx("span", { children: t('app.title') }), _jsx("button", { onClick: () => selectLanguage(lang === 'en' ? 'hi' : 'en'), class: "text-brand font-semibold hover:underline min-h-[36px] flex items-center px-2", children: lang === 'en' ? 'हिंदी में बदलें' : 'Switch to English' })] }) })] }));
}
